### ISSUE TITLE
New kernel signalling tests failing on Jenkins

### ISSUE THREAD

**Issue by takluyver** [jupyter/jupyter_client#111]
It looks like the `bash` subprocesses are failing to start for some reason. This is on the jack-of-none job ([buildlog](https://jenkins.jupyter.org/job/jack-of-none/122/console)).

```
======================================================================
FAIL: test_signal_kernel_subprocesses (jupyter_client.tests.test_kernelmanager.TestKernelManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/ipython_genutils/testing/decorators.py", line 186, in skipper_func
    return f(*args, **kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/jupyter_client/tests/test_kernelmanager.py", line 104, in test_signal_kernel_subprocesses
    self.assertEqual(reply['user_expressions']['poll'], [None] * N)
nose.proxy.AssertionError: Lists differ: [127, 127, 127, 127, 127] != [None, None, None, None, None]

First differing element 0:
127
None

- [127, 127, 127, 127, 127]
+ [None, None, None, None, None]
-------------------- >> begin captured logging << --------------------
root: DEBUG: Found kernel signaltest in /tmp/tmpve4aomr4/jupyter_data/kernels
root: DEBUG: Native kernel (python3) available from /var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/ipykernel/resources
root: DEBUG: Starting kernel: ['/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/bin/python3.4', '-m', 'jupyter_client.tests.signalkernel', '-f', '/tmp/tmpb3_8dhxp.json']
root: DEBUG: Connecting to: tcp://127.0.0.1:41234
root: DEBUG: connecting shell channel to tcp://127.0.0.1:43459
root: DEBUG: Connecting to: tcp://127.0.0.1:43459
root: DEBUG: connecting iopub channel to tcp://127.0.0.1:55729
root: DEBUG: Connecting to: tcp://127.0.0.1:55729
root: DEBUG: connecting stdin channel to tcp://127.0.0.1:48693
root: DEBUG: Connecting to: tcp://127.0.0.1:48693
root: DEBUG: connecting heartbeat channel to tcp://127.0.0.1:59474
--------------------- >> end captured logging << ---------------------
```

**Comment by minrk** [comment]
Jenkins had a totally bonkers PATH, such that `bash` subprocesses couldn't find `/bin/sleep`. Fixed now.
