### ISSUE TITLE
Test failure in jack-of-none builds

### ISSUE THREAD

**Issue by takluyver** [jupyter/jupyter_client#171]
This started failing today, and appears to be reproducible. I'm not sure what might have changed to cause it:

```
======================================================================
FAIL: test_signal_kernel_subprocesses (jupyter_client.tests.test_kernelmanager.TestKernelManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/ipython_genutils/testing/decorators.py", line 186, in skipper_func
    return f(*args, **kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.4/site-packages/jupyter_client/tests/test_kernelmanager.py", line 104, in test_signal_kernel_subprocesses
    self.assertEqual(reply['user_expressions']['poll'], [None] * N)
nose.proxy.AssertionError: Lists differ: [127, 127, 127, 127, 127] != [None, None, None, None, None]

First differing element 0:
127
None

- [127, 127, 127, 127, 127]
+ [None, None, None, None, None]
```

**Comment by takluyver** [comment]
Unfortunately, while #177 made this test run again, it's still failing.

**Comment by minrk** [comment]
It was a configuration problem on Jenkins, where PATH was messed up as:

```bash
export PATH=\${PATH}:\${HOME}/.nave
```

(note escapes, preventing $PATH from being extended) instead of

```bash
export PATH=${PATH}:${HOME}/.nave
```

in `/var/lib/jenkins/.bashrc`. Not sure how or why Jenkins messed that up.

[All green now](https://jenkins.jupyter.org/job/jack-of-none/370/).

**Comment by takluyver** [comment]
Thanks for digging into it!

**Comment by takluyver** [comment]
I've fixed this again, and found that it was coming from ansible. ipython/ipython-ansible-jenkins@b9cb3fd39322719825043b2908f0d3642835203c

**Comment by minrk** [comment]
thanks!
