### ISSUE TITLE
get_msg raises Empty

### ISSUE THREAD

**Issue by jakirkham** [jupyter/jupyter_client#197]
Seeing this issue when trying to run a notebook through `runipy` of late and am trying to understand if there is something change that I'm missing and need to address.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/runipy/notebook_runner.py", line 232, in run_notebook
    self.run_cell(cell)
  File "/opt/conda/lib/python2.7/site-packages/runipy/notebook_runner.py", line 151, in run_cell
    msg = self.kc.get_iopub_msg(timeout=1)
  File "/opt/conda/lib/python2.7/site-packages/jupyter_client/client.py", line 81, in get_iopub_msg
    return self.iopub_channel.get_msg(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
Empty
```

**Comment by minrk** [comment]
Empty means there was no message arriving on the Queue in the allotted time. That's suggesting that no IOPub message is arriving within one second. It's possible that timeout is too short for the given circumstance, but it looks like runipy hardcodes a timeout of 1s where perhaps it should be configurable or at least more forgiving.

**Comment by jakirkham** [comment]
Yep that seems reasonable. Will start working on some sort of config for this.

**Comment by Juanlu001** [comment]
For reference: do you mean https://github.com/paulgb/runipy/blob/2c78f91/runipy/notebook_runner.py#L155 ?

**Comment by JaneMiso** [comment]
Sorry, but I still meet the problem, is anyone could help me?

**Comment by davidbrochart** [comment]
Do you use runipy, or nbclient/nbconvert?

**Comment by JaneMiso** [comment]
I use runipy

**Comment by davidbrochart** [comment]
Any reason for doing so? As stated in [the project's main page](https://github.com/paulgb/runipy), runipy is deprecated and unmaintained.
Could you use nbconvert or nbclient instead?

**Comment by JaneMiso** [comment]
Yes, I tried the nbconvert but I got the error: _Cell execution timed out_. But I haven't try the nbclient.

**Comment by davidbrochart** [comment]
nbconvert will use nbclient to execute the notebook in the next release.
It would be interesting to try out with nbclient, as it now uses asynchronous programming and this might have improved the handling of timeouts.
Or maybe the cell code does have a timeout issue. Could you share the cell code, or tell a little bit more about what it is doing?

**Comment by JaneMiso** [comment]
Sorry for the late reply, I tried the nbclient and set the timeout to -1. It is working now. 

The workflow of this .ipynb is loading data from tfrecords format, build and train a convolutional neural network, final evaluate this model on testing data. During the training process, I used checkpoints to save the model when it gets lower val_loss.
And the issue showed when tried to load a model saved as model_best.h5 after the fitting finished.

**Comment by jakirkham** [comment]
Should we go ahead and close then?
