### ISSUE TITLE
write_connection_file fails in long running notebook server

### ISSUE THREAD

**Issue by kynan** [jupyter/jupyter_client#199]
I'm on 64bit Linux, running `jupyter notebook` in a miniconda 3 environment (Python 3.5):

```
jupyter_client            4.3.0                    py35_0    conda-forge
jupyter_console           5.0.0                    py35_0    conda-forge
jupyter_core              4.1.0                    py35_0    conda-forge
```

When I leave the notebook server idle for extended periods (days, at least hours) I experience the following failure when creating a new notebook (Python 3 kernel):

```
[I 18:09:47.052 NotebookApp] Creating new notebook in
[E 18:09:48.373 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File ".../notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File ".../tornado/gen.py", line 1015, in run
        value = future.result()
      File ".../tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File ".../tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File ".../notebook/services/sessions/handlers.py", line 62, in post
        kernel_id=kernel_id))
      File ".../tornado/gen.py", line 1015, in run
        value = future.result()
      File ".../tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File ".../tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File ".../notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_name)
      File ".../tornado/gen.py", line 1015, in run
        value = future.result()
      File ".../tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File ".../tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File ".../notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File ".../tornado/gen.py", line 1015, in run
        value = future.result()
      File ".../tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File ".../tornado/gen.py", line 285, in wrapper
        yielded = next(result)
      File ".../notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File ".../jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File ".../jupyter_client/manager.py", line 224, in start_kernel
        self.write_connection_file()
      File ".../jupyter_client/connect.py", line 406, in write_connection_file
        kernel_name=self.kernel_name
      File ".../jupyter_client/connect.py", line 134, in write_connection_file
        with open(fname, 'w') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/run/user/4150/jupyter/kernel-f440f50e-d0b9-4ea7-95bb-55300ef90602.json'
[E 18:09:48.650 NotebookApp] {
      "Content-Type": "application/json",
      "Content-Length": "76",
      "Dnt": "1",
      "Origin": "http://localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "...",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=python3",
      "X-Requested-With": "XMLHttpRequest",
      "Host": "localhost:8888",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Language": "en-GB,en;q=0.8,en-US;q=0.6,de;q=0.4,fr;q=0.2"
    }
[E 18:09:48.650 NotebookApp] 500 POST /api/sessions (::1) 481.34ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=python3
```

The issue turns out to be that the directory `/run/user/4150/jupyter` is missing. I suppose `/run/user/$UID` is cleaned up regularly by the system. Creating the directory or restarting the notebook server resolves the issue.

**Comment by takluyver** [comment]
> I suppose /run/user/$UID is cleaned up regularly by the system.

Aha, something I'd never noticed before in [the spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

> Files in this directory MAY be subjected to periodic clean-up. To ensure that your files are not removed, they should have their access time timestamp modified at least once every 6 hours of monotonic time or the 'sticky' bit should be set on the file.

That sounds like it could cause what you see.

**Comment by minrk** [comment]
#201 sets sticky bit on connection files.

**Comment by n8henrie** [comment]
I am having this issue on a Linode server running Arch 4.9.50, notebook 5.2.1. The `/run/user/$UID/jupyter` gets deleted after a couple hours. Any reason this patch might be failing to work? My user owns the jupyter directory, I’ll see if u can figure out how to check if the sticky bit is being set or not.

**Comment by n8henrie** [comment]
Manually set the sticky bit on the directory, and it still got deleted.

**Comment by takluyver** [comment]
It's not clear from the spec whether setting the sticky bit on the directory is enough, or it should be set on individual files.

What version of `jupyter_client` do you have installed? If it's >= 5.0, it should be setting the sticky bit for you. If you do have the latest version and the sticky bit doesn't get set, please feel free to open a new bug about that.
