### ISSUE TITLE
Kernel is listed as available, but cannot be used

### ISSUE THREAD

**Issue by ProgVal** [jupyter/jupyter_client#224]
I installed my kernel like this (the `kernel.json` is from [the doc](https://jupyter-client.readthedocs.io/en/latest/wrapperkernels.html#example)):

```
$ cat decmd/shell/kernel.json 
{
    "argv":["python","-m","decmd.shell", "-f", "{connection_file}"],
    "display_name":"Decmd Shell"
}
$ jupyter kernelspec install decmd/shell --name decmd_shell --user
[InstallKernelSpec] Removing existing kernelspec in /home/user/.local/share/jupyter/kernels/decmd_shell
[InstallKernelSpec] Installed kernelspec decmd_shell in /home/user/.local/share/jupyter/kernels/decmd_shell
```

My kernel is listed as available:

```
$ jupyter kernelspec list                                                               
Available kernels:
  python3        /home/user/.local/lib/python3.5/site-packages/ipykernel/resources
  decmd_shell    /home/user/.local/share/jupyter/kernels/decmd_shell
```

However, I cannot use it:

```
$ jupyter console --kernel demcd_shell                                                  
Traceback (most recent call last):
  File "/home/dev-these/.local/lib/python3.5/site-packages/jupyter_client/kernelspec.py", line 173, in get_kernel_spec
    resource_dir = d[kernel_name.lower()]
KeyError: 'demcd_shell'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev-these/.local/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/home/dev-these/.local/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/dev-these/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/home/dev-these/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/dev-these/.local/lib/python3.5/site-packages/jupyter_console/app.py", line 137, in initialize
    self.init_shell()
  File "/home/dev-these/.local/lib/python3.5/site-packages/jupyter_console/app.py", line 105, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/home/dev-these/.local/lib/python3.5/site-packages/jupyter_client/consoleapp.py", line 334, in initialize
    self.init_kernel_manager()
  File "/home/dev-these/.local/lib/python3.5/site-packages/jupyter_client/consoleapp.py", line 288, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/home/dev-these/.local/lib/python3.5/site-packages/jupyter_client/manager.py", line 230, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/home/dev-these/.local/lib/python3.5/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/home/dev-these/.local/lib/python3.5/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/dev-these/.local/lib/python3.5/site-packages/jupyter_client/kernelspec.py", line 175, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named demcd_shell
```

---

Python version: 3.5.2
Jupyter versions:

```
$ pip3 list | grep jup
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.2.0)
```

**Comment by ProgVal** [comment]
It seems to work without an underscore:

```
$ jupyter kernelspec install decmd/shell --name test --user
[InstallKernelSpec] Removing existing kernelspec in /home/dev-these/.local/share/jupyter/kernels/test
[InstallKernelSpec] Installed kernelspec test in /home/dev-these/.local/share/jupyter/kernels/test
$ jupyter console --kernel test                            
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/dev-these/decmd/decmd/shell/__main__.py", line 5, in <module>
    from . import kernel
  File "decmd/shell/kernel.py", line 1, in <module>
    raise NotImplementedError()
NotImplementedError
```

**Comment by minrk** [comment]
Sorry for the slow reply. This is strange. I can run kernels with an underscore in the name. Can you show the contents of the kernelspecs that have been installed? Do they differ?

**Comment by ProgVal** [comment]
> Can you show the contents of the kernelspecs that have been installed?

Yes:

```
$ ls ~/.local/share/jupyter/kernels/
decmd_shell  test
```

> Do they differ?

Not according to `diff ~/.local/share/jupyter/kernels/decmd_shell ~/.local/share/jupyter/kernels/test`.

**Comment by takluyver** [comment]
Can you try these in Python:

```python
from jupyter_client import kernelspec
kernelspec.find_kernel_specs()  # What output does this give?
kernelspec.get_kernel_spec('decmd_shell')  # Does this throw an error?
```

**Comment by ProgVal** [comment]
```
Python 3.5.2+ (default, Dec 13 2016, 14:16:35) 
[GCC 6.2.1 20161124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jupyter_client import kernelspec
>>> kernelspec.find_kernel_specs()
{'test': '/home/dev-these/.local/share/jupyter/kernels/test', 'python3': '/home/dev-these/.local/lib/python3.5/site-packages/ipykernel/resources', 'decmd_shell': '/home/dev-these/.local/share/jupyter/kernels/decmd_shell'}
>>> kernelspec.get_kernel_spec('decmd_shell')
<jupyter_client.kernelspec.KernelSpec object at 0x7f743a49a198>
```

**Comment by takluyver** [comment]
Do you have any config that could be affecting `jupyter_console`?

If not, or you're not sure, can you edit the installed kernelspec.py just before [this line](https://github.com/jupyter/jupyter_client/blob/4.4.0/jupyter_client/kernelspec.py#L175), to print `d` and `self.kernel_dirs`?

**Comment by ProgVal** [comment]
Oops, it was a typo: `demcd_shell` instead of `decmd_shell`

Sorry

**Comment by takluyver** [comment]
And I thought we had an interesting bug to hunt :-P
