### ISSUE TITLE
DeprecationWarning when executing cells after importing pyRserve

### ISSUE THREAD

**Issue by flying-sheep** [jupyter/jupyter_client#257]
after establishing a [pyRserve] connection, i get the following when executing any cell:

```pytb
/home/icb/philipp.angerer/.local/lib/python3.5/json/encoder.py:198: DeprecationWarning: Interpreting naive datetime as local 2017-05-05 16:52:02.642545. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)
```

this is because the package calls `warnings.filterwarnings('once', category=DeprecationWarning)`.

bad behavior, but we should fix jupyter_client to not trigger warnings in the first place.

[pyRserve]: https://github.com/ralhei/pyRserve

**Comment by Carreau** [comment]
I'm unsure this is something we can do. If DeprecationWarnings are enabled they just do to StdErr. We can't just discard the stream. 

We also do enable DeprecationWarning in IPython, but only if they land in user-code. It might be something that pyRserver want to do by adding the `module` keyword to their filter.

**Comment by flying-sheep** [comment]
oh, my point is to just fix the DeprecationWarning that is raised by this project’s code.

**Comment by Carreau** [comment]
Ah, Let me see if we can have a stack-trace.

**Comment by Carreau** [comment]
```
Traceback (most recent call last):
  File "/Users/bussonniermatthias/dev/ipykernel/ipykernel/kernelbase.py", line 225, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/bussonniermatthias/dev/ipykernel/ipykernel/kernelbase.py", line 404, in execute_request
    ident=ident)
  File "/Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/jupyter_client/session.py", line 712, in send
    to_send = self.serialize(msg, ident)
  File "/Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/jupyter_client/session.py", line 619, in serialize
    self.pack(msg['metadata']),
  File "/Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/jupyter_client/session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,
  File "/Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/zmq/utils/jsonapi.py", line 40, in dumps
    s = jsonmod.dumps(o, **kwargs)
  File "/Users/bussonniermatthias/anaconda/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/bussonniermatthias/anaconda/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/bussonniermatthias/anaconda/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/jupyter_client/jsonutil.py", line 90, in date_default
    obj = _ensure_tzinfo(obj)
  File "/Users/bussonniermatthias/anaconda/lib/python3.6/site-packages/jupyter_client/jsonutil.py", line 43, in _ensure_tzinfo
    stacklevel=4)
DeprecationWarning: Interpreting naive datetime as local 2017-05-07 10:34:38.635161. Please add timezone info to timestamps.
```
