### ISSUE TITLE
launch_kernal is failing with FileNotFound, pointing to a removed venv's python3

### ISSUE THREAD

**Issue by liavkoren** [jupyter/jupyter_client#269]
Hi! I seem to have gotten my system into some sort of weird state that's messing the jupyter client jup. It looks like a removed venv's is being pointed to, even from within new, clean venvs. The removed virtualenv was named `cnn` and you can see in the first line something is trying to point to `cnn`'s python3. 

I can reproduce this error on my system just by doing:
```bash
$ python3 -m venv cheshire
$ source cheshire/bin/activate
$ pip3 install jupyter
$ jupyter notebook
```

Which gets me:

```
[E 19:59:11.447 NotebookApp] Failed to run command:
    ['/Users/liavkoren/Envs/cnn/bin/python3', '-m', 'ipykernel', '-f', '/Users/liavkoren/Library/Jupyter/runtime/kernel-ca0a261e-3c4e-42b0-9a69-96769d5e3caa.json']
        PATH='/Users/liavkoren/cheshire/bin:/Users/liavkoren/cheshire/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/opt/openssl@1.1/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/mysql/bin:/usr/local/bin:/usr/local/mysql-5.6.14-osx10.7-x86_64/bin:/usr/local/bin/terraform_0.6.12_darwin_amd64:/Users/liavkoren/bin:/Users/liavkoren/dev/vmportal:/usr/local/opt/coreutils/libexec/gnubin:/Users/liavkoren/Envs/vmportal/bin:/Users/liavkoren/Downloads/redis-3.0.3/src:/Users/liavkoren/Downloads/terraform_0.6.6_darwin_amd64:/usr/local/octave/3.8.0/bin:/Users/liavkoren/dev/go_workspace/bin:/Users/liavkoren/.rvm/bin:/usr/local/sbin:/Applications/Postgres.app/Contents/Versions/9.3/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': '/Users/liavkoren', 'start_new_session': True}

[E 19:59:11.448 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/notebook/base/handlers.py", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 75, in post
        type=mtype))
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 94, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/jupyter_client/manager.py", line 257, in start_kernel
        **kw)
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/jupyter_client/manager.py", line 203, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/Users/liavkoren/cheshire/lib/python3.6/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/liavkoren/Envs/cnn/bin/python3'
[E 19:59:11.460 NotebookApp] {
      "Host": "localhost:8889",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "X-Xsrftoken": "2|d17dae40|b3705ea3a9e503d5c33798e6a51e12ea|1498150298",
      "X-Requested-With": "XMLHttpRequest",
      "Referer": "http://localhost:8889/notebooks/Untitled.ipynb?kernel_name=python3",
      "Content-Length": "91",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1498261982|23:username-localhost-8888|44:MjAyNmMwZGRiYTY0NDM0OGE0YTUyNDE1NGJlNGY0ZjU=|f1846ba3fa68b526ee59e10a723c11051276111e3be222a085aa2940049c93e3\"; _xsrf=2|d17dae40|b3705ea3a9e503d5c33798e6a51e12ea|1498150298; username-localhost-8889=\"2|1:0|10:1498262341|23:username-localhost-8889|44:MzBkZjgzYTFlZTNiNGNlYTkyYjJlYmZhZWY3N2Q5ZjE=|25a473613261097aa1d5432976ac4941026a08efc660ff28edb43b32f40e6953\"",
      "Dnt": "1",
      "Connection": "keep-alive"
    }
[E 19:59:11.460 NotebookApp] 500 POST /api/sessions (::1) 62.21ms referer=http://localhost:8889/notebooks/Untitled.ipynb?kernel_name=python3
```

What's going on? I can recreate the `cnn` venv, which should at least letstart new notebooks, but then I get [other random bugs](https://github.com/sn0wle0pard/ipytracer/issues/14).

**Comment by takluyver** [comment]
Run `jupyter kernelspec list` - it should show you the location of the kernelspec, which is probably pointing to the old virtualenv. You can just remove that directory, it should detect your current Python by default. Or you can [install a new kernelspec](http://ipython.readthedocs.io/en/stable/install/kernel_install.html) in its place.

**Comment by liavkoren** [comment]
Thank you, removing the kernal directory seems to have resolved this issue, altho now I'm running into weird javascript ipywidgets issues. : ) That's a different repo's problem, tho.
