### ISSUE TITLE
Directory for kernel json files is not created, leading to kernel errors

### ISSUE THREAD

**Issue by c-f-h** [jupyter/jupyter_client#351]
I don't know if this is the proper subproject to report this in, but the stacktrace would suggest so.

Here's my situation:

1. I log in from home via ssh to my work computer, setting up a tunnel with `-L 8888:localhost:8888`, and start `jupyter notebook`. I work with Python kernels in a notebook normally. I leave Jupyter running.

2. Later, I physically log in at my work computer (which I ssh'ed into before) and connect to Jupyter. I can view notebooks and open them, but as soon as I try to run calculations, I get a red "Kernel Error" box.
Here's the stacktrace on the server:

```
[E 11:00:17.806 NotebookApp] Uncaught exception POST /api/sessions (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='::1', headers={'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/6
4.0.3282.167 Safari/537.36', 'Content-Length': '92', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'Referer': 'http://localhost:8888/notebooks/_Untitled.ipynb', 'Cookie': '_xsrf=2|d10df97e|7a06e7c2738f6aed896d9f8dbb55b20b|15
18429637; username-localhost-8888="2|1:0|10:1520244014|23:username-localhost-8888|44:N2IwZDk0NWFlNWY0NGM3OGFlMDQwN2MzM2VjY2E1YzY=|1124565de65981a2ace77da5408158ae205a25c0a58c967c4be8dc193cd0db5f"', 'Connection': 'keep-alive', 'Host': 'loc
alhost:8888', 'X-Requested-With': 'XMLHttpRequest', 'Accept-Language': 'en-US,en;q=0.9,de;q=0.8,bg;q=0.7', 'Origin': 'http://localhost:8888', 'X-Xsrftoken': '2|d10df97e|7a06e7c2738f6aed896d9f8dbb55b20b|1518429637', 'Content-Type': 'applic
ation/json', 'Accept-Encoding': 'gzip, deflate, br'})                         
    Traceback (most recent call last):   
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/gen.py", line 1055, in run           
        value = future.result()                                                  
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)          
      File "<string>", line 4, in raise_exc_info
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/notebook/services/sessions/handlers.py", line 73, in post
        type=mtype))
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/notebook/services/sessions/handlers.py", line 73, in post
        type=mtype))
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 148, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/jupyter_client/manager.py", line 238, in start_kernel
        self.write_connection_file()
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/jupyter_client/connect.py", line 472, in write_connection_file
        kernel_name=self.kernel_name
      File "/home/hilbert/chofreither/.local/lib64/python3.5/site-packages/jupyter_client/connect.py", line 137, in write_connection_file
        with open(fname, 'w') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/run/user/2004/jupyter/kernel-af5cf9bb-2172-48a1-9239-7e8b7891afe9.json'
[W 11:00:17.811 NotebookApp] Unhandled error
[E 11:00:17.811 NotebookApp] {
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36",
      "Content-Length": "92",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Referer": "http://localhost:8888/notebooks/_Untitled.ipynb",
      "Cookie": "_xsrf=2|d10df97e|7a06e7c2738f6aed896d9f8dbb55b20b|1518429637; username-localhost-8888=\"2|1:0|10:1520244014|23:username-localhost-8888|44:N2IwZDk0NWFlNWY0NGM3OGFlMDQwN2MzM2VjY2E1YzY=|1124565de65981a2ace77da5408158ae205a25
c0a58c967c4be8dc193cd0db5f\"",
      "Connection": "keep-alive",
      "Host": "localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "Accept-Language": "en-US,en;q=0.9,de;q=0.8,bg;q=0.7",
      "Origin": "http://localhost:8888",
      "X-Xsrftoken": "2|d10df97e|7a06e7c2738f6aed896d9f8dbb55b20b|1518429637",
      "Content-Type": "application/json",
      "Accept-Encoding": "gzip, deflate, br"
    }
```

3. I notice that the directory `/run/user/2004/` exists, but not `/run/user/2004/jupyter/`, so I manually create that directory.

4. Now everything works!

It's very confusing to me that this works over ssh, but then not when logged in directly. If, on the physical machine, I kill jupyter and restart it locally, kernels also work. It's only if I start jupyter via ssh that it fails later on.

**Comment by takluyver** [comment]
Thanks for the detailed report. I guess that the `/run/user/2004` directory is being removed and recreated at some point. It's supposed to stay around as long as you're logged in, but confusingly it seems to be possible to 'log out' while Jupyter is still running.

It's probably sufficient to create the `jupyter` subdirectory if needed before writing the connection file. This is the right repo to do that.

**Comment by c-f-h** [comment]
When I check `mount`, I see this:

    tmpfs on /run/user/2004 type tmpfs (rw,nosuid,nodev,relatime,size=3283092k,mode=700,uid=2004,gid=1001)

I'm not the sysadmin of this machine, but I think your guess that it's recreated on each login due to being a `tmpfs` might be the reason.

**Comment by sebma** [comment]
@c-f-h Hi, I have the same pb.

Workaround: `mkdir /run/user/$UID/jupyter`

In the title of this issue, can you be a little more specific by replacing "Directory for kernel json files is not created" by "Directory for kernel json files gets removed" ?

Thanks :)

**Comment by c-f-h** [comment]
Hi @sebma,
I don't think that Jupyter actually removes the directory, I think this is due to my system's configuration. As far as I can tell, the Jupyter bug is that it does not get explicitly created, not that it gets removed.
