### ISSUE TITLE
msgpack appears to be unsupported in ipython config 

### ISSUE THREAD

**Issue by vaughnkoch** [jupyter/jupyter_client#400]
### Problem
Using msgpack as the packer/unpacker for ipykernel raises exceptions when loading a Jupyter notebook.

### Repro
Set packer/unpacker in ipython_config.py. Restart `jupyter notebook` and load a blank notebook. In my case, before restarting JN, I also deleted /Users/******/Library/Jupyter/runtime to remove any lingering .json files, and closed all Jupyter browser windows. 

My msgpack code in ipython_config.py:

```
# Example code from https://github.com/minrk/.jupyter/blob/master/jupyter_notebook_config.py
try:
  import msgpack
except ImportError:
  pass
else:
  c.Session.packer = 'msgpack.packb'
  c.Session.unpacker = 'msgpack.unpackb'
```

### Background

I'm building an extension to IPython which sometimes requires a large amount of data (e.g. 300k database records) to be sent to the client, which currently takes 7-15 seconds to serialize and send to the client via json. So, I'd like to use msgpack (or bson I guess). 

I'm aware of @takluyver's comments in https://github.com/jupyter/jupyter_client/issues/292#issuecomment-328374945. However, that limits ipykernel comm use only to small messages. Is there a future where you would support msgpack or other unpackers?

### My environment

```
python -c "import IPython; print(IPython.sys_info())"

{'commit_hash': 'dd83a2163',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/*********/data/virtualenvs/*******/lib/python3.7/site-packages/IPython',
 'ipython_version': '6.5.0',
 'os_name': 'posix',
 'platform': 'Darwin-16.7.0-x86_64-i386-64bit',
 'sys_executable': '/Users/*********/data/virtualenvs/*******/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.7.0 (default, Jul 23 2018, 20:24:19) \n'
                '[Clang 9.0.0 (clang-900.0.39.2)]'}

$ pip freeze |ack --noenv 'jupyter|ipykernel|ipython'
ipykernel==4.8.2
ipython==6.5.0
ipython-genutils==0.2.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
jupyter-react==0.1.3
jupyterthemes==0.19.4
```

### Exceptions caused by using msgpack:

```
[I 18:13:22.472 NotebookApp] Kernel started: 3acd8fd3-633d-49c2-a8c5-db27b40a6d88
[IPKernelApp] ERROR | Failed to load connection file: '/Users/******/Library/Jupyter/runtime/kernel-3acd8fd3-633d-49c2-a8c5-db27b40a6d88.json'
Traceback (most recent call last):
  File "/Users/******/data/virtualenvs/*******/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/******/data/virtualenvs/*******/lib/python3.7/site-packages/jupyter_client/session.py", line 540, in _check_packers
    assert unpacked == msg
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/******/data/virtualenvs/*******/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 224, in init_connection_file
    self.load_connection_file()
  File "/Users/******/data/virtualenvs/*******/lib/python3.7/site-packages/jupyter_client/connect.py", line 495, in load_connection_file
    self.load_connection_info(info)
  File "/Users/******/data/virtualenvs/*******/lib/python3.7/site-packages/jupyter_client/connect.py", line 519, in load_connection_info
    self.session.key = cast_bytes(info['key'])
  File "/Users/******/data/virtualenvs/*******/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/Users/******/data/virtualenvs/*******/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/Users/******/data/virtualenvs/*******/lib/python3.7/site-packages/jupyter_client/connect.py", line 354, in _session_default
    return Session(parent=self)
  File "/Users/******/data/virtualenvs/*******/lib/python3.7/site-packages/jupyter_client/session.py", line 482, in __init__
    self._check_packers()
  File "/Users/******/data/virtualenvs/*******/lib/python3.7/site-packages/jupyter_client/session.py", line 548, in _check_packers
    msg.format(packer=self.packer, unpacker=self.unpacker, e=e, jsonmsg=jsonmsg)
ValueError: unpacker 'msgpack.unpackb' could not handle output from packer 'msgpack.packb': 
```

### Runtime files 

Some tokens etc redacted.

```
ls /Users/*******/Library/Jupyter/runtime |xargs -I FOO sh -c 'echo FOO; echo ; cat FOO'

kernel-3acd8fd3-633d-49c2-a8c5-db27b40a6d88.json
{
  "shell_port": 55933,
  "iopub_port": 55934,
  "stdin_port": 55935,
  "control_port": 55936,
  "hb_port": 55937,
  "ip": "127.0.0.1",
  "key": "******************************",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": "python3"
}

nbserver-82555.json
{
  "base_url": "/",
  "hostname": "localhost",
  "notebook_dir": "/****/******",
  "password": false,
  "pid": 82555,
  "port": 8888,
  "secure": false,
  "token": "*********************",
  "url": "http://localhost:8888/"
}

notebook_cookie_secret
********************* (redacted)
```

**Comment by minrk** [comment]
msgpack's Python defaults aren't actually round-trip safe. There is a wrapper package `msgpacku` that does actually return the same object that the serializer serialized, so you can use it:

```python
c.Session.packer = 'msgpacku.packb'
c.Session.unpacker = 'msgpacku.unpackb'
```

This is equivalent to passing `raw=False, use_bin_type=True`, which should ~always be used with msgpack, but isn't the default for backward-compatibility reasons. Additionally, this must be specified in both the kernel config and the client config. Negotiating serialization is not part of the protocol.

That said, using msgpack for serialization can only improve the communication between the kernel and notebook server. It cannot be applied to the server->browser connection, which is usually the slower one anyway, so this is unlikely to have as much impact as you might like.

A more likely useful change is to use binary buffers, if you can, since these don't get reserialized at all, no matter what the message serialization is, and doesn't require any configuration coordination between multiple components. Are you using comms to send this data, pure display-data messages?

**Comment by vaughnkoch** [comment]
Yup, I'm using comms to send data between the kernel and my Jupyter extension. Using binary buffers would be great, actually. Is there any documentation on how to use them (or an example?) Also, do you have a recommended method to pass unserialized data between Python and JS, other than json.dumps to a string buffer on both sides?

I installed msgpack/msgpacku and added these lines to ipython_config.py and ipython_notebook_config.py:

```
c.Session.packer = 'msgpacku.packb'
c.Session.unpacker = 'msgpacku.unpackb'
```
I get different errors though. Maybe there is some config that I missed somewhere. 

New exceptions:
```
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 206, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/jupyter_client/session.py", line 926, in deserialize
    header = self.unpack(msg_list[1])
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/jupyter_client/session.py", line 559, in <lambda>
    self.unpack = lambda s: unpack(s)
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/msgpacku.py", line 19, in unpackb
    return msgpack.unpackb(buf, **kwargs)
  File "msgpack/_unpacker.pyx", line 208, in msgpack._unpacker.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
[E 00:28:43.894 NotebookApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
        callback(*args, **kwargs)
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 388, in record_activity
        msg = session.deserialize(fed_msg_list)
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/jupyter_client/session.py", line 926, in deserialize
        header = self.unpack(msg_list[1])
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/jupyter_client/session.py", line 105, in <lambda>
        json_unpacker = lambda s: jsonapi.loads(s)
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/zmq/utils/jsonapi.py", line 54, in loads
        s = s.decode('utf8')
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 0: invalid start byte
[E 00:28:43.896 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
        self._handle_recv()
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
        self._run_callback(callback, msg)
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
        callback(*args, **kwargs)
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 388, in record_activity
        msg = session.deserialize(fed_msg_list)
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/jupyter_client/session.py", line 926, in deserialize
        header = self.unpack(msg_list[1])
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/jupyter_client/session.py", line 105, in <lambda>
        json_unpacker = lambda s: jsonapi.loads(s)
      File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/zmq/utils/jsonapi.py", line 54, in loads
        s = s.decode('utf8')
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 0: invalid start byte
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(33, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(33, 1)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 388, in record_activity
    msg = session.deserialize(fed_msg_list)
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/jupyter_client/session.py", line 926, in deserialize
    header = self.unpack(msg_list[1])
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/jupyter_client/session.py", line 105, in <lambda>
    json_unpacker = lambda s: jsonapi.loads(s)
  File "/Users/********/data/virtualenvs/features/lib/python3.7/site-packages/zmq/utils/jsonapi.py", line 54, in loads
    s = s.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 0: invalid start byte
```
