### ISSUE TITLE
5.3.3 seems to be broken

### ISSUE THREAD

**Issue by lramey** [jupyter/jupyter_client#480]
I get this:

Traceback (most recent call last):

  File "C:\Users\lramey\AppData\Roaming\Alteryx\Miniconda\envs\test23\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "C:\Users\lramey\AppData\Roaming\Alteryx\Miniconda\envs\test23\lib\runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "C:\Users\lramey\AppData\Roaming\Alteryx\Miniconda\envs\test23\lib\site-packages\ipykernel_launcher.py", line 16, in <module>

    app.launch_new_instance()

  File "C:\Users\lramey\AppData\Roaming\Alteryx\Miniconda\envs\test23\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance

    app.initialize(argv)

  File "<C:\Users\lramey\AppData\Roaming\Alteryx\Miniconda\envs\test23\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize

  File "C:\Users\lramey\AppData\Roaming\Alteryx\Miniconda\envs\test23\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error

    return method(app, *args, **kwargs)

  File "C:\Users\lramey\AppData\Roaming\Alteryx\Miniconda\envs\test23\lib\site-packages\ipykernel\kernelapp.py", line 530, in initialize

    self.write_connection_file()

  File "C:\Users\lramey\AppData\Roaming\Alteryx\Miniconda\envs\test23\lib\site-packages\ipykernel\kernelapp.py", line 227, in write_connection_file

    iopub_port=self.iopub_port, control_port=self.control_port)

  File "C:\Users\lramey\AppData\Roaming\Alteryx\Miniconda\envs\test23\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file

    with secure_write(fname) as f:

  File "C:\Users\lramey\AppData\Roaming\Alteryx\Miniconda\envs\test23\lib\contextlib.py", line 81, in __enter__

    return next(self.gen)

  File "C:\Users\lramey\AppData\Roaming\Alteryx\Miniconda\envs\test23\lib\site-packages\jupyter_client\connect.py", line 100, in secure_write

    win32_restrict_file_to_user(fname)

  File "C:\Users\lramey\AppData\Roaming\Alteryx\Miniconda\envs\test23\lib\site-packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user

    import win32api

ModuleNotFoundError: No module named 'win32api'

There is no such package in Conda land. (at least not according to https://anaconda.org/search

My create command was:
conda create -n test23  python=3.6.8 ipython ipykernel pandas

**Comment by lramey** [comment]
conda install pywin32

fixed the virtual env and jupyter is working again. Looks like a blown dependency file in the 5.3.3 release.

**Comment by kevin-bates** [comment]
Thanks for the update.  I believe @minrk addressed this earlier today: https://github.com/conda-forge/jupyter_client-feedstock/pull/30.  Not sure how long things take to surface.

**Comment by samvanbrussel** [comment]
5.3.2 and 5.3.3 are broken. I've run pip install jupyter-client==5.3.1 to fix it.

Reproduce the problem:
Have a clean install of Anaconda 2019.07

`Write-Host "Updating Anaconda ..."
conda update --all --yes

Write-Host "Updating pip ..."
python -m pip install --upgrade pip

Write-Host "Updating python packages ..."
pip list | ForEach-Object { pip install --upgrade $_.Split()[0] }

Write-Host "Cleaning Anaconda ..."
conda clean --all --yes

jupyter notebook`

Start a new Python 3 Notebook and you get a Kernel error

> Traceback (most recent call last):
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\jupyter_client\connect.py", line 100, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\sam.vanbrussel\AppData\Local\Programs\Anaconda\lib\site-packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by kylekeppler** [comment]
Updating to `conda-forge/win-64::jupyter_client-5.3.3-py37_1` manually fixed this for me.

`conda install jupyterlab` left me with `conda-forge/noarch::jupyter_client-5.3.3-py_0`
