### ISSUE TITLE
kernel client blocks indefinitely during gc.collect() call

### ISSUE THREAD

**Issue by markwaddle** [jupyter/jupyter_client#482]
after a `BlockingClient` execution request that times out, `gc.collect()` hangs indefinitely

see the repro at https://gist.github.com/markwaddle/af87e1d314fad4021d8d25c0b7c59cb7

```python
import gc
from jupyter_client import KernelManager


def start_kernel():
    kernel_manager = KernelManager()
    kernel_manager.start_kernel()
    kernel_client = kernel_manager.blocking_client()
    kernel_client.execute_interactive(code='', silent=False, allow_stdin=False,
            output_hook=lambda x: print('output:', x), timeout=.1)


if __name__ == '__main__':
    try:
        start_kernel()
    except Exception as e:
        print('exception:', e)
    print('garbage collecting - process hangs indefinitely here')
    gc.collect()
    print('done - never reaches here')
```

**Comment by markwaddle** [comment]
interestingly, if you place the body of the `start_kernel` function directly under main, instead of calling the function, the hang does not occur.

**Comment by markwaddle** [comment]
and this is where it hangs:
```
Exception ignored in: <function Context.__del__ at 0x1040d7d08>
Traceback (most recent call last):
  File "/Users/mark/.local/share/virtualenvs/kernel_test-kiveVYPU/lib/python3.7/site-packages/zmq/sugar/context.py", line 50, in __del__
    self.term()
  File "zmq/backend/cython/context.pyx", line 91, in zmq.backend.cython.context.Context.term
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
```

**Comment by markwaddle** [comment]
on a side note, does anyone know why the `BlockingClient. execute_interactive` call times out? is there something else i should be doing before making that call?

**Comment by markwaddle** [comment]
i've determined that a call to `kernel_client.stop_channels()`, prior to the gc.collect(), will allow the collect to complete
