### ISSUE TITLE
jupyter_client inside Flatpak: "KeyError: 'kernel_dirs'"

### ISSUE THREAD

**Issue by cvfosammmm** [jupyter/jupyter_client#505]
I'm trying to use jupyter_client inside a Flatpak. I can install it (and ipykernel) with pip. The error happens when I call `get_all_specs` from my app. I guess that is because I have to use a custom directory ("--prefix=${FLATPAK_DEST}") with pip, because the Python path is "read-only". Calling `jupyter_client.kernelspec.find_kernel_specs()` I get an empty list, even though ipykernel is installed. Must I somehow extend the path? Any ideas?

Here's the traceback:
```Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'kernel_dirs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/porto", line 40, in do_activate
    print(kernel_spec_manager.get_all_specs())
  File "/app/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 253, in get_all_specs
    d = self.find_kernel_specs()
  File "/app/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 165, in find_kernel_specs
    for kernel_dir in self.kernel_dirs:
  File "/app/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/app/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/app/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 159, in _kernel_dirs_default
    dirs.append(os.path.join(get_ipython_dir(), 'kernels'))
  File "/app/lib/python3.7/site-packages/IPython/utils/path.py", line 255, in get_ipython_dir
    from IPython.paths import get_ipython_dir
  File "/app/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/app/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/app/lib/python3.7/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/app/lib/python3.7/site-packages/IPython/core/ultratb.py", line 115, in <module>
    from IPython.core import debugger
  File "/app/lib/python3.7/site-packages/IPython/core/debugger.py", line 38, in <module>
    from IPython.utils import PyColorize
  File "/app/lib/python3.7/site-packages/IPython/utils/PyColorize.py", line 47, in <module>
    from .colorable import Colorable
  File "/app/lib/python3.7/site-packages/IPython/utils/colorable.py", line 12, in <module>
    import pygments
ModuleNotFoundError: No module named 'pygments'```

**Comment by MSeal** [comment]
This looks like you're execution environment and your install paths differ. Likely you installed into a site-packages that isn't being added to the python path.

I'd strongly consider making a [python venv](https://docs.python.org/3/library/venv.html), installing everything there and running your program with that venv activated. This is doing essentially what you were doing manually, by isolating an install path to an writable location isolated by name. See if the error goes away after that.

**Comment by cvfosammmm** [comment]
Thanks a lot, it works with venv, awesome!
