### ISSUE TITLE
Failed to set sticky bit

### ISSUE THREAD

**Issue by maddukurisrinivasarao** [jupyter/jupyter_client#510]
Using Jupyter client version '5.3.3' giving following error message every time when notebook connects to a kernel
Runtime warning: failed to set sticky bit on /users/<username>/.local/share/jupyter/runtime/kernel-xxxxxx.json

**Comment by seq101** [comment]
Has this been resolved? I am getting this same issue. Someone please help!

**Comment by kevin-bates** [comment]
Since there's been a fair amount of churn near this area of the code, could you please confirm you're using jupyter_client >= `5.3.4` and jupyter_core >= `4.6.1`?  

That said, this particular scenario can be file system-sensitive.  Do you know what kind of filesystem is in use for your runtime data?  In particular, is it mounted rather than local to the machine?

**Comment by seq101** [comment]
I really appreciate your prompt response. I am not mounted, but local to the machine. I upgraded the jypyter notebook and then another problem started. I even tried a fresh install of conda in another directory and I am wondering if that is also contributing to this this error.

Versions are all here.
jupyter core     : 4.6.3
jupyter-notebook : 5.7.8
qtconsole        : 4.5.5
ipython          : 5.9.0
ipykernel        : 4.5.2
jupyter client   : 5.3.4
jupyter lab      : 0.33.11
nbconvert        : 5.6.1
ipywidgets       : 6.0.0
nbformat         : 4.3.0
traitlets        : 4.3.3

**Comment by kevin-bates** [comment]
Thanks - your version info seems good.  Could you please provide the console output of the Notebook server when this occurs?

**Comment by seq101** [comment]
[I 11:23:47.665 NotebookApp] Kernel started: 65fb5892-aa2e-4735-a9db-f8e6817d5567
/home/psingh4/software/anaconda2/lib/python2.7/site-packages/jupyter_client/connect.py:167: RuntimeWarning: Failed to set sticky bit on u'/home/psingh4/.local/share/jupyter/runtime/kernel-65fb5892-aa2e-4735-a9db-f8e6817d5567.json': [Errno 22] Invalid argument: '/home/psingh4/.local/share/jupyter/runtime/kernel-65fb5892-aa2e-4735-a9db-f8e6817d5567.json'
Probably not a big deal, but runtime files may be cleaned up periodically.
  RuntimeWarning,
Traceback (most recent call last):
  File "/home/psingh4/software/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/psingh4/software/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/psingh4/software/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/psingh4/software/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/psingh4/.local/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/psingh4/software/anaconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/psingh4/software/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/psingh4/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/psingh4/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 226, in dispatch_shell
    self.pre_handler_hook()
  File "/home/psingh4/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 241, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
ValueError: signal only works in main thread
ERROR:tornado.general:Uncaught exception in zmqstream callback

**Comment by kevin-bates** [comment]
I think the sticky bit portion, although annoying, is just that.  I think this code may be protecting against automatic cleanup that can occur on some Unix systems, iirc something related to `XDG_RUNTIME_DIR`.  [The `stat` structure that is in use defines `S_ISVTX`](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/connect.py#L141-L165), yet `chmod()` has heartburn over it or perhaps some other permissions presently on the file (but more like `S_ISVTX`).

The bigger issue is the rest of the traceback that repeats.  For that, [this issue](https://github.com/jupyter/jupyter_console/issues/163) implies it might be worthwhile upgrading `ipykernel` and it looks like your version (`4.5.2`) may be a little stale - so I'd give that a shot.

**Comment by maddukurisrinivasarao** [comment]
@kevin-bates I am using following

jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : 4.5.5
ipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.3
jupyter lab      : not installed
nbconvert        : 5.6.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.2

**Comment by kevin-bates** [comment]
Hi @maddukurisrinivasarao - but are you seeing anything other than the sticky bit warning message?   The reference to `ipykernel` is relative to the uncaught exception, not the sticky bit.

Btw, is the sticky bit warning message produced the same as for @seq101 - `[Errno 22] Invalid argument`?

And is your runtime directory on any kind of mounted filesystem?

**Comment by maddukurisrinivasarao** [comment]
@kevin-bates yes, I am getting "[Errno 22] Invalid argument". Also "Replacing stale connection" warning i.e reported at https://github.com/jupyter/notebook/issues/5225

yes, I am using a mounted filesystem.

**Comment by seq101** [comment]
updating the kernel did it. Wierd thing is I had tried to update the kernel using conda ealier but this time I tried updating it using pip and that did it. THANK YOU SO MUICH! I spent 5 hrs on this..
pip install --upgrade ipykernel

**Comment by kevin-bates** [comment]
@maddukurisrinivasarao - sorry for the lack of response on your notebook issue.  I just responded - albeit not very helpful (other than a data point).

Given you're on a mounted filesystem, I wonder if that is triggering the sticky-bit warning message.  We have found filesystem-sensitivity in performing some operations.  However, those tend to manifest themselves when setting the general permissions which occurs prior to setting the sticky bit.

Some changes have been made in jupyter_client and jupyter_core in writing the kernel.json file, but given your information, I don't think an upgrade of those modules is necessary.

**Comment by mattburnham** [comment]
Thankyou so much. This resolved the issue as well "pip install --upgrade ipykernel" after about 2 days of investigation.

I started having this issue (among others) ever since a manadtory security update to Windows 10 to version 1909, build 18363.752 a month ago.  I uninstalled / reinstalled Anaconda about 5 times. The notebook version kept on telling me it was 5.2.2 each time. then I followed these instructions to delete everything "notebook":

https://stackoverflow.com/questions/59992785/jupyter-notebook-version
Type pip install pip-autoremove and pip-autoremove jupyter -y. Then check what still installed there with conda list . If you still have installations, type pip3 uninstall jupyter , pip3 uninstall jupyter_core , pip3 uninstall jupyter-client , pip3 uninstall jupyter-console , pip3 uninstall notebook , pip3 uninstall qtconsole , pip3 uninstall nbconvert , pip3 uninstall nbformat

I also ran `conda update anaconda` after the fresh Anaconda install before doing 
`pip install --upgrade ipykernel` to finally get it to work.

Good Luck & Thanks

**Comment by wesnm** [comment]
Hi, just noticed this open issue. On FreeBSD, the "sticky bit" is valid only for directories. From chmod(2):

> The FreeBSD VM system totally ignores the sticky bit (S_ISVTX) for executables.  On UFS-based file systems (FFS, LFS) the sticky bit may only be set upon directories.

The man page says UFS, but it is also true for ZFS as well, which is generally the only other relevant FS that might be encountered on a FreeBSD system. As a result, trying to set the sticky bit on the kernel-xxxxx.json file will always throw OSError with Errno 79 (EFTYPE). So if `sys.platform.startswith("freebsd") == True` then the error message should probably be suppressed.
