### ISSUE TITLE
Bug: TypeError: ChannelABC() takes no arguments

### ISSUE THREAD

**Issue by SanPen** [jupyter/jupyter_client#531]
Hi, 

I have an application that depends on Jupyter client. The application is called GridCal.

The minimal test is this code:

```

from qtconsole.rich_jupyter_widget import RichJupyterWidget
from qtconsole.inprocess import QtInProcessKernelManager


class ConsoleWidget(RichJupyterWidget):
    """
    Convenience class for a live IPython console widget.
    We can replace the standard banner using the customBanner argument
    """

    def __init__(self, customBanner=None, *args, **kwargs):
        RichJupyterWidget.__init__(self, *args, **kwargs)

        if customBanner is not None:
            self.banner = customBanner

        self.font_size = 6
        self.gui_completion = 'droplist'
        self.kernel_manager = QtInProcessKernelManager()
        self.kernel_manager.start_kernel(show_banner=False)
        self.kernel_manager.kernel.gui = 'qt'
        self.kernel_client = kernel_client = self._kernel_manager.client()
        kernel_client.start_channels()

        def stop():
            kernel_client.stop_channels()
            self.kernel_manager.shutdown_kernel()
            # guisupport.get_app_qt().exit()

        self.exit_requested.connect(stop)

    def push_vars(self, variableDict):
        """
        Given a dictionary containing name / value pairs, push those variables
        to the IPython console widget
        """
        self.kernel_manager.kernel.shell.push(variableDict)

    def clear(self):
        """
        Clears the terminal
        """
        self._control.clear()

        # self.kernel_manager

    def print_text(self, text):
        """
        Prints some plain text to the console
        """
        self._append_plain_text(text)

    def execute_command(self, command):
        """
        Execute a command in the frame of the console widget
        """
        self._execute(command, False)


if __name__ == '__main__':
    try:
        from qtconsole.qt import QtWidgets
    except:
        from qtconsole.qtconsoleapp import QtWidgets
    app = QtWidgets.QApplication([])
    widget = ConsoleWidget()
    widget.show()
    app.exec_()

```

The error trace is this:

```
Traceback (most recent call last):
  File "/home/santi/Documentos/GitHub/GridCal/src/GridCal/Gui/ConsoleWidget.py", line 68, in <module>
    widget = ConsoleWidget()
  File "/home/santi/Documentos/GitHub/GridCal/src/GridCal/Gui/ConsoleWidget.py", line 24, in __init__
    self.kernel_client = kernel_client = self._kernel_manager.client()
  File "/home/santi/Descargas/Python-3.8.2/Compiled/lib/python3.8/site-packages/qtconsole/base_frontend_mixin.py", line 63, in kernel_client
    if kernel_client.channels_running:
  File "/home/santi/Descargas/Python-3.8.2/Compiled/lib/python3.8/site-packages/jupyter_client/client.py", line 141, in channels_running
    self.control_channel.is_alive())
  File "/home/santi/Descargas/Python-3.8.2/Compiled/lib/python3.8/site-packages/jupyter_client/client.py", line 199, in control_channel
    self._control_channel = self.control_channel_class(socket, self.session, self.ioloop)
TypeError: ChannelABC() takes no arguments
```

A pip freeze throws the versions of every package in my distro:

```
attrs==19.3.0
backcall==0.1.0
branca==0.4.0
certifi==2019.11.28
chardet==3.0.4
cycler==0.10.0
decorator==4.4.2
dill==0.3.1.1
et-xmlfile==1.0.1
folium==0.10.1
geographiclib==1.50
geopy==1.21.0
h5py==2.10.0
idna==2.9
ipykernel==5.1.4
ipython==7.13.0
ipython-genutils==0.2.0
jdcal==1.4.1
jedi==0.16.0
Jinja2==2.11.1
joblib==0.14.1
jupyter-client==6.0.0
jupyter-core==4.6.3
kiwisolver==1.1.0
llvmlite==0.31.0
MarkupSafe==1.1.1
matplotlib==3.2.0
more-itertools==8.2.0
networkx==2.4
numba==0.48.0
numpy==1.18.1
openpyxl==3.0.3
packaging==20.3
pandas==1.0.1
parso==0.6.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
pluggy==0.13.1
POAP==0.1.26
prompt-toolkit==3.0.4
ptyprocess==0.6.0
PuLP==2.0
py==1.8.1
pyDOE==0.3.8
pyDOE2==1.3.0
Pygments==2.6.1
pyparsing==2.4.6
PySide2==5.14.1
pySOT==0.2.3
pytest==5.4.1
python-dateutil==2.8.1
pytz==2019.3
pyzmq==19.0.0
qtconsole==4.7.1
QtPy==1.9.0
requests==2.23.0
scikit-learn==0.22.2.post1
scipy==1.4.1
shiboken2==5.14.1
six==1.14.0
smopy==0.0.7
tabulate==0.8.3
tornado==6.0.4
traitlets==4.3.3
urllib3==1.25.8
wcwidth==0.1.8
xlrd==1.2.0
xlwt==1.3.0
```

**Comment by davidbrochart** [comment]
I think it's related to #523. This should be fixed in https://github.com/ipython/ipykernel/pull/489.

**Comment by SanPen** [comment]
great, thanks

**Comment by SanPen** [comment]
Hi, this is happening again. Exact same error.

Mu pip freeze is:

```
alabaster==0.7.12
appdirs==1.4.3
asn1crypto==1.2.0
atomicwrites==1.3.0
attrs==19.1.0
Babel==2.7.0
backcall==0.1.0
bleach==3.1.5
branca==0.3.1
cakephp-theme==1.0.2
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
Click==7.0
conda==4.7.12
conda-package-handling==1.3.11
configparser==3.7.4
cryptography==2.7
cupy==6.5.0
cupy-cuda101==6.3.0
cvxopt==1.2.0
cvxoptklu==1.2.1
cycler==0.10.0
Cython==0.29.14
decorator==4.4.0
defusedxml==0.6.0
dill==0.3.0
doc8==0.8.0
docutils==0.15.2
entrypoints==0.3
enum34==1.1.10
et-xmlfile==1.0.1
fastrlock==0.4
folium==0.10.0
fortranformat==0.2.5
geographiclib==1.49
geopy==1.20.0
h5py==2.9.0
idna==2.8
imagesize==1.1.0
importlib-metadata==0.19
ipykernel==5.1.2
ipython==7.7.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jdcal==1.4.1
jedi==0.15.1
Jinja2==2.10.3
joblib==0.13.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
kiwisolver==1.1.0
libarchive-c==2.8
llvmlite==0.30.0
lxml==4.5.0
Mako==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.1
mistune==0.8.4
mkl-fft==1.0.14
mkl-random==1.0.2
mkl-service==2.3.0
more-itertools==7.2.0
mpld3==0.3
mpmath==1.1.0
nbconvert==5.6.1
nbformat==5.0.6
networkx==2.3
nose==1.3.7
notebook==6.0.3
numba==0.46.0
numba-scipy==0.2.0
numpy==1.16.4
opencv-python==4.2.0.34
openpyxl==2.6.3
ordereddict==1.1
packaging==19.2
pandas==0.25.1
pandocfilters==1.4.2
parso==0.5.1
pbr==5.4.3
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
pluggy==0.12.0
POAP==0.1.26
prometheus-client==0.7.1
prompt-toolkit==2.0.9
ptyprocess==0.6.0
PuLP==1.6.10
py==1.8.0
pybind11==2.5.0
pycosat==0.6.3
pycparser==2.19
pycuda==2019.1.2
pyDOE==0.3.8
pyDOE2==1.2.1
Pygments==2.4.2
pyOpenSSL==19.0.0
pypardiso==0.2.2
pyparsing==2.4.2
pyproj==2.6.0
pyrsistent==0.16.0
PySide2==5.13.2
PySocks==1.7.0
pySOT==0.2.3
pytest==5.1.1
python-dateutil==2.8.0
python-docx==0.8.10
pytools==2019.1.1
pytz==2019.3
pyzmq==18.1.0
qtconsole==4.7.4
QtPy==1.9.0
requests==2.22.0
restructuredtext-lint==1.3.0
ruamel-yaml==0.15.46
scikit-learn==0.21.3
scikit-umfpack==0.3.2
scipy==1.3.1
selenium==3.141.0
Send2Trash==1.5.0
shiboken2==5.13.2
six==1.12.0
smopy==0.0.7
snowballstemmer==2.0.0
Sphinx==2.2.1
sphinx-bootstrap-theme==0.7.1
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
stdeb==0.9.0
stem==1.8.0
stevedore==1.31.0
tabulate==0.8.3
terminado==0.8.3
testpath==0.4.4
tilemapbase==0.4.6
tornado==6.0.3
tqdm==4.32.1
traitlets==4.3.2
urllib3==1.24.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.5.1
xlrd==1.2.0
xlwt==1.3.0
zipp==0.6.0

```

**Comment by SanPen** [comment]
I would suggest to include the minimal example as a test somewhere

**Comment by MSeal** [comment]
Your pip freeze has `ipykernel==5.1.2` which is even older from Aug 2019. You need to use the later version, >5.2.0 I think, to not have the error.

Going to close for now, as it's likely solved and really an ipykernel issue and not a jupyter_client one.
