### ISSUE TITLE
TypeError: object() takes no parameters: still proiblem with 6.1.0

### ISSUE THREAD

**Issue by 3fon3fonov** [jupyter/jupyter_client#534]
Unfortunately, the new release did not solve the problem below:

See https://github.com/3fon3fonov/exostriker/issues/55 

It works fine with e.g. jupyter_client==5.3.1

===== 2020.03.20 09:03:45 =====
Traceback (most recent call last):
  File "es_gui.py", line 7222, in <module>
    main() 
  File "es_gui.py", line 7205, in main
    window = Exo_striker()
  File "es_gui.py", line 6712, in __init__
    self.console_widget = ConsoleWidget_embed(font_size = 9)
  File "./lib/Jupyter_emb.py", line 24, in __init__
    self.kernel_client = self._kernel_manager.client()
  File "/usr/local/lib/python3.6/dist-packages/qtconsole/base_frontend_mixin.py", line 63, in kernel_client
    if kernel_client.channels_running:
  File "/usr/local/lib/python3.6/dist-packages/jupyter_client/client.py", line 141, in channels_running
    self.control_channel.is_alive())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_client/client.py", line 200, in control_channel
    socket, self.session, self.ioloop
TypeError: object() takes no parameters

**Comment by davidbrochart** [comment]
Yes, a release has to be made in https://github.com/ipython/ipykernel.

**Comment by 3fon3fonov** [comment]
Oh, I did not get that... Since the problem appears in jupyter_client/client.py, 
I thought that a general fix must be done in the jupyter-client, not in the ipykernel.

I thought that https://github.com/ipython/ipykernel/pull/489 is just a temporary fix.

Ok then, let's wait for a new release of the ipykernel to see if things will be sorted out.

Thanks!

**Comment by 3fon3fonov** [comment]
After the new release of ipykernel everything seems to be OK!

Closing, thanks!
