### ISSUE TITLE
Uncaught exception nbconvert

### ISSUE THREAD

**Issue by gioarma** [jupyter/jupyter_client#537]
Versions:
- nbconvert: 5.6.1
- jupyterlab: 2.0.1
- jupyterlab_server: 1.0.7
-jupyter_client: 6.1.2

When launching jupyterlab from the terminal I get this error. I looked up other issues regarding this error, but I could not fix it with what I found. I tried to downgrade tornado, to close all browser tabs and restart, to uninstall and reinstall jupyter lab, but nothing.
Any suggestions?

```
[E 17:22:08.473 LabApp] Uncaught exception GET /api/nbconvert?1585412527069 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/nbconvert?1585412527069', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/anaconda3/lib/python3.7/site-packages/notebook/services/nbconvert/handlers.py", line 21, in get
        exporter_class = base.get_exporter(exporter_name)
      File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 98, in get_exporter
        return entrypoints.get_single('nbconvert.exporters', name).load()
      File "/opt/anaconda3/lib/python3.7/site-packages/entrypoints.py", line 82, in load
        mod = import_module(self.module_name)
      File "/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/opt/anaconda3/lib/python3.7/site-packages/nbinteract/__init__.py", line 13, in <module>
        from .plotting import *
      File "/opt/anaconda3/lib/python3.7/site-packages/nbinteract/plotting.py", line 17, in <module>
        import bqplot as bq
      File "/opt/anaconda3/lib/python3.7/site-packages/bqplot/__init__.py", line 64, in <module>
        from .figure import *
      File "/opt/anaconda3/lib/python3.7/site-packages/bqplot/figure.py", line 33, in <module>
        from ipywidgets import DOMWidget, register, widget_serialization
    ModuleNotFoundError: No module named 'ipywidgets'
[W 17:22:08.474 LabApp] Unhandled error
[E 17:22:08.475 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Authorization": "token 8b8bcdda14c7cb43cc5ba9afb64da739d5fb33cda210b2c4",
      "Sec-Fetch-Dest": "empty",
      "X-Xsrftoken": "2|462172fb|529270d122239eecda2b04f508595d06|1583947627",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en,it-IT;q=0.9,it;q=0.8,en-US;q=0.7,fr;q=0.6",
      "Cookie": "_xsrf=2|462172fb|529270d122239eecda2b04f508595d06|1583947627; username-localhost-8888=\"2|1:0|10:1585412526|23:username-localhost-8888|44:NzQ3OWFlYjI0ODkwNGYwYzkzNjVmYzViZjg4ZmJkZWM=|90e1b895169a988023b2aa3beb73e328a1133f64ac8b30e7582aaac9de312647\""
    }
```

**Comment by davidbrochart** [comment]
Maybe install ipywidgets?

**Comment by gioarma** [comment]
Yes! That solved the problem, thank you!
