### ISSUE TITLE
Exception in callback Error when closing the kernel

### ISSUE THREAD

**Issue by ahmadmustafaanis** [jupyter/jupyter_client#575]
OS: Ubuntu 18.04 

Latest Jupyter notebook

WHen I close a kernel from command prompt using ctrl+c, it closes the kernel and throws and exception. It was not doing it when I had `tensorflow 2.2`, but i switched to `tensorflow 2.0` and it is giving this jupyter error.

```error
Shutdown this notebook server (y/[n])? y
[C 18:45:49.608 NotebookApp] Shutdown confirmed
[I 18:45:49.610 NotebookApp] Shutting down 1 kernel
[I 18:45:50.313 NotebookApp] Kernel shutdown: b62da79b-ca59-43f3-ba21-a021e6330235
[I 18:45:50.314 NotebookApp] Shutting down 0 terminals
[I 18:45:50.319 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel b62da79b-ca59-43f3-ba21-a021e6330235 restarted
[E 18:45:50.321 NotebookApp] Exception in callback <bound method KernelRestarter.poll of <jupyter_client.ioloop.restarter.IOLoopKernelRestarter object at 0x7fc102298510>>
    Traceback (most recent call last):
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/jupyter_client/restarter.py", line 113, in poll
        self.kernel_manager.restart_kernel(now=True, newports=newports)
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/jupyter_client/manager.py", line 442, in restart_kernel
        self.shutdown_kernel(now=now, restart=True)
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/jupyter_client/manager.py", line 383, in shutdown_kernel
        self._kill_kernel()
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/jupyter_client/manager.py", line 487, in _kill_kernel
        raise RuntimeError("Cannot kill kernel. No kernel is running!")
    RuntimeError: Cannot kill kernel. No kernel is running!
(deep) ahmad@ahmad-HP-Laptop-15-da1xxx:~$ 
```
How to solve this error. Thanks

**Comment by MSeal** [comment]
6.1.7 release has this change added.
