### ISSUE TITLE
6.2.0: sphinx warnings and errors

### ISSUE THREAD

**Issue by kloczek** [jupyter/jupyter_client#662]
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.0.2
Initializing GitHub plugin
making output directory... done
loading intersphinx inventory from http://ipython.readthedocs.io/en/stable/objects.inv...
intersphinx inventory has moved: http://ipython.readthedocs.io/en/stable/objects.inv -> https://ipython.readthedocs.io/en/stable/objects.inv
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 9 added, 0 changed, 0 removed
reading sources... [100%] wrapperkernels
WARNING: autodoc: failed to import method 'KernelClient.get_shell_msg' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 412, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: type object 'KernelClient' has no attribute 'get_shell_msg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 318, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2606, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 428, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: get_shell_msg

WARNING: autodoc: failed to import method 'KernelClient.get_iopub_msg' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 412, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: type object 'KernelClient' has no attribute 'get_iopub_msg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 318, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2606, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 428, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: get_iopub_msg

WARNING: autodoc: failed to import method 'KernelClient.get_stdin_msg' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 412, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: type object 'KernelClient' has no attribute 'get_stdin_msg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 318, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2606, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 428, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: get_stdin_msg

/home/tkloczko/rpmbuild/BUILD/jupyter_client-6.2.0/docs/wrapperkernels.rst:137: WARNING: duplicate object description of MyKernel, other instance in wrapperkernels, use :noindex: for one of them
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... jupyter_client.1 { messaging kernels wrapperkernels api/index api/kernelspec api/manager api/client changelog } /home/tkloczko/rpmbuild/BUILD/jupyter_client-6.2.0/docs/kernels.rst:: WARNING: "table cell spanning" not supported
done
build succeeded, 5 warnings.
```

**Comment by kloczek** [comment]
Outdated
