### ISSUE TITLE
7.3.2: documentation build output with call traces when is used sphinx 5.0.1

### ISSUE THREAD

**Issue by kloczek** [jupyter/jupyter_client#798]
Looks like latest `jupyter-client` documentation is not fully ready to be used with latest sphinx 5.0.1
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.0.1
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
Initializing GitHub plugin
making output directory... done
myst v0.17.2: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['html_image'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, footnote_transition=True, sub_delimiters=('{', '}'), words_per_minute=200)
loading intersphinx inventory from http://ipython.readthedocs.io/en/stable/objects.inv...
intersphinx inventory has moved: http://ipython.readthedocs.io/en/stable/objects.inv -> https://ipython.readthedocs.io/en/stable/objects.inv
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 13 added, 0 changed, 0 removed
reading sources... [100%] wrapperkernels
WARNING: autodoc: failed to import class 'KernelClient' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import class 'BlockingKernelClient' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import method 'kernelspec.KernelSpec.to_json' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import method 'kernelspec.KernelSpecManager.find_kernel_specs' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import method 'kernelspec.KernelSpecManager.get_all_specs' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import method 'kernelspec.KernelSpecManager.get_kernel_spec' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import method 'kernelspec.KernelSpecManager.install_kernel_spec' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import class 'KernelManager' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import class 'MultiKernelManager' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import function 'run_kernel' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import class 'provisioning.provisioner_base.KernelProvisionerBase' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import class 'provisioning.local_provisioner.LocalProvisioner' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import class 'provisioning.factory.KernelProvisionerFactory' from module 'jupyter_client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

WARNING: autodoc: failed to import method 'kernelbase.Kernel.send_response' from module 'ipykernel'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 61, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/ipykernel/__init__.py", line 5, in <module>
    from .connect import *  # noqa
  File "/usr/lib/python3.8/site-packages/ipykernel/connect.py", line 11, in <module>
    import jupyter_client
  File "/usr/lib/python3.8/site-packages/jupyter_client/__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py", line 4, in <module>
    from traitlets import Type
  File "/usr/lib/python3.8/site-packages/traitlets/__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "/usr/lib/python3.8/site-packages/traitlets/_version.py", line 7, in <module>
    assert __version__ == (
AssertionError
```
After there are already reported warnings in //github.com/jupyter/jupyter_client/issues/777

**Comment by kloczek** [comment]
Looks like that affects as well pytest
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-jupyter-client-7.3.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-jupyter-client-7.3.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/jupyter_client-7.3.2, configfile: pyproject.toml, testpaths: jupyter_client/tests/
plugins: timeout-2.1.0, asyncio-0.18.2
timeout: 300.0s
timeout method: signal
timeout func_only: False
asyncio: mode=auto
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
______________________________________________________________________ ERROR collecting test session _______________________________________________________________________
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:843: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
jupyter_client/__init__.py:8: in <module>
    from .asynchronous import AsyncKernelClient  # noqa
jupyter_client/asynchronous/__init__.py:1: in <module>
    from .client import AsyncKernelClient  # noqa
jupyter_client/asynchronous/client.py:4: in <module>
    from traitlets import Type
/usr/lib/python3.8/site-packages/traitlets/__init__.py:5: in <module>
    from ._version import __version__, version_info
/usr/lib/python3.8/site-packages/traitlets/_version.py:7: in <module>
    assert __version__ == (
E   AssertionError
========================================================================= short test summary info ==========================================================================
ERROR  - AssertionError
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.15s =============================================================================
```

**Comment by davidbrochart** [comment]
I think it should be fixed in https://github.com/ipython/traitlets/pull/739, but it has not been released yet.

**Comment by davidbrochart** [comment]
Actually it has been release in traitlets `5.2.2.post1`, what version do you have?

**Comment by kloczek** [comment]
I'm using 5.2.2.

**Comment by davidbrochart** [comment]
> I don't see 5.2.2.post1 tag in https://github.com/ipython/traitlets/tags

Me neither, that's why I was confused, but it's on PyPI: https://pypi.org/project/traitlets.

> I'm using 5.2.2.

Please update to `5.2.2.post1`.

**Comment by davidbrochart** [comment]
> Just please push that tag to the git repo yum (and why not 5.2.3? smiley )

I don't have rights on the traitlets package, I think @blink1073 does.

**Comment by blink1073** [comment]
Done: https://github.com/ipython/traitlets/releases/tag/5.2.2.post1

**Comment by kloczek** [comment]
New `traitlets` 5.2.2.post1 looks good.👍 
Now only retest `jupyter-client` 😋

**Comment by kloczek** [comment]
OK closing.
Build with new `traitlets` solves reported issue.

Thank you very much 👍 😃 
Closing.
```console
client-7.3.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/jupyter_client-7.3.2, configfile: pyproject.toml, testpaths: jupyter_client/tests/
plugins: asyncio-0.18.2, timeout-2.1.0
asyncio: mode=auto
timeout: 300.0s
timeout method: signal
timeout func_only: False
collected 180 items

jupyter_client/tests/test_adapter.py ...........................                                                                                                     [ 15%]
jupyter_client/tests/test_client.py ........                                                                                                                         [ 19%]
jupyter_client/tests/test_connect.py ...........                                                                                                                     [ 25%]
jupyter_client/tests/test_jsonutil.py .....                                                                                                                          [ 28%]
jupyter_client/tests/test_kernelapp.py .                                                                                                                             [ 28%]
jupyter_client/tests/test_kernelmanager.py .....................s.s.s............                                                                                    [ 50%]
jupyter_client/tests/test_kernelspec.py .............                                                                                                                [ 57%]
jupyter_client/tests/test_localinterfaces.py .                                                                                                                       [ 57%]
jupyter_client/tests/test_manager.py .                                                                                                                               [ 58%]
jupyter_client/tests/test_multikernelmanager.py ..............................                                                                                       [ 75%]
jupyter_client/tests/test_provisioning.py ...........                                                                                                                [ 81%]
jupyter_client/tests/test_public_api.py ....                                                                                                                         [ 83%]
jupyter_client/tests/test_restarter.py ........                                                                                                                      [ 87%]
jupyter_client/tests/test_session.py .........s...........                                                                                                           [ 99%]
jupyter_client/tests/test_ssh.py .                                                                                                                                   [100%]

=========================================================================== slowest 10 durations ===========================================================================
19.27s call     jupyter_client/tests/test_kernelmanager.py::TestParallel::test_start_sequence_kernels[tcp]
19.12s call     jupyter_client/tests/test_kernelmanager.py::TestParallel::test_start_sequence_kernels[ipc]
18.10s call     jupyter_client/tests/test_restarter.py::test_async_restarter_gives_up[tcp]
18.10s call     jupyter_client/tests/test_restarter.py::test_async_restarter_gives_up[ipc]
12.30s call     jupyter_client/tests/test_kernelmanager.py::TestParallel::test_start_parallel_process_kernels[tcp]
12.29s call     jupyter_client/tests/test_kernelmanager.py::TestParallel::test_start_sequence_process_kernels[tcp]
12.20s call     jupyter_client/tests/test_kernelmanager.py::TestParallel::test_start_parallel_thread_kernels[tcp]
9.11s call     jupyter_client/tests/test_restarter.py::test_async_restart_check[ipc]
9.10s call     jupyter_client/tests/test_restarter.py::test_restart_check[ipc]
8.19s call     jupyter_client/tests/test_kernelmanager.py::TestKernelManagerShutDownGracefully::test_async_signal_kernel_subprocesses[signaltest-no-terminate-install_kernel_dont_terminate-_ShutdownStatus.SigkillRequest]
========================================================================= short test summary info ==========================================================================
SKIPPED [1] jupyter_client/tests/test_kernelmanager.py:369: IPC transport is currently not working for this test!
SKIPPED [1] jupyter_client/tests/test_kernelmanager.py:385: IPC transport is currently not working for this test!
SKIPPED [1] jupyter_client/tests/test_kernelmanager.py:401: IPC transport is currently not working for this test!
SKIPPED [1] jupyter_client/tests/test_session.py:309: could not import 'msgpack': No module named 'msgpack'
================================================================ 176 passed, 4 skipped in 234.22s (0:03:54) ================================================================
```
