### ISSUE TITLE
AssertionError on matplotlib interactive mode

### ISSUE THREAD

**Issue by hs-vc** [jupyter/jupyter_client#952]
I got Assertion error message in ~/.jupyter/log when I create plot with matplotlib library in jupyter notebook and zoom any area in the plot. Because of this error, the zoom functionality doesn't work properly. 

Following is reproducible jupyter notebook code.

```python
import matplotlib.pyplot as plt

%matplotlib nbagg

fig, ax = plt.subplots()
ax.plot([1,2,3], [1,2,3])

# And then zoom any areay
```

Below is error message in ~/.jupyter/log created every time zooming  any area in the plot.
```python
[E 04:10:45.852 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/opt/python/py3.10/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 634, in _handle_events
        self._handle_recv()
      File "/opt/python/py3.10/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 663, in _handle_recv
        self._run_callback(callback, msg)
      File "/opt/python/py3.10/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/opt/python/py3.10/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/opt/python/py3.10/lib/python3.10/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/opt/python/py3.10/lib/python3.10/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/opt/python/py3.10/lib/python3.10/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/opt/python/py3.10/lib/python3.10/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/opt/python/py3.10/lib/python3.10/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/opt/python/py3.10/lib/python3.10/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/opt/python/py3.10/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/opt/python/py3.10/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
```
I have conducted tests using the latest notebook version (v6.5.4) and jupyter_client (v8.2.0), and it seems that this issue is specifically related to jupyter_client v8.2.0. The error does not occur in jupyter_client versions 7.x

**Comment by ccordoba12** [comment]
By interactive you mean the Notebook backend or the Qt, Tk, etc ones?

**Comment by hs-vc** [comment]
> By interactive you mean the Notebook backend or the Qt, Tk, etc ones?

I mean notebook backend.
