### ISSUE TITLE
multikernelmanager  update_env error

### ISSUE THREAD

**Issue by sky-fun** [jupyter/jupyter_client#990]
run jupyter lab in remote server `jupyter lab --ip myip --port 8989 --allow-root`
when open link in local browser ,it shows `Error Starting Kernel`  `Unhandled error`

```
Traceback (most recent call last):
  File "/opt/apps/local/lib64/python3/dist-packages/tornado/web.py", line 1786, in _execute
    result = await result
  File "/usr/local/softwares/miniconda3/envs/notebook/lib/python3.8/site-packages/jupyter_server/services/sessions/handlers.py", line 172, in patch
    await sm.update_session(session_id, **changes)
  File "/usr/local/softwares/miniconda3/envs/notebook/lib/python3.8/site-packages/jupyter_server/services/sessions/sessionmanager.py", line 469, in update_session
    self.kernel_manager.update_env(kernel_id=kernel_id, env=self.get_kernel_env(path, name))
  File "/usr/local/softwares/miniconda3/envs/notebook/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 226, in update_env
    self._kernels[kernel_id].update_env(env)
TypeError: update_env() takes 1 positional argument but 2 were given
```

**Comment by paridee** [comment]
I get the same error within a JupyterHub environment, as temporary workaround I downgraded the following 2 libraries and seems to work:
jupyter_client==8.3.0
jupyter_server==2.7.0

waiting for a fix...

**Comment by krassowski** [comment]
Hi all, thanks for the report, this is also tracked in https://github.com/jupyter-server/jupyter_server/issues/1345.

**Comment by gmocquet** [comment]
Same error here
